
# Database connection
# -------------------
database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/epaylater?useEncoding=true&amp;characterEncoding=UTF-8
  user: root
  password: root
  properties:
     charSet: UTF-8
  validationQuery: "/*  Health Check */ SELECT 1"

server:
  requestLog:
    timeZone: UTC
    appenders:
     - type: console
       threshold: ALL
       timeZone: UTC
       target: stdout
     - type: file
       currentLogFilename: build/logs/testApp-access.log
       archive: true
       archivedLogFilenamePattern: build/logs/testApp-access-%d.log
       archivedFileCount: 5

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: build/logs/testApp.log
      archive: true
      archivedLogFilenamePattern: build/logs/testApp-%d.log
      archivedFileCount: 5
      timeZone: UTC